### ISSUE TITLE
Calculator 1.12.2 - 5.0.5 : Server crashes on starting

### ISSUE THREAD

**Issue by guillaumearm** [SonarSonic/Calculator#364] opened 2018-06-03 11:32 UTC
Hi.

with Calculator 5.0.5 : the minecraft server crashes on starting
with Calculator 5.0.4 : it works

here is my server stacktrace : 

```
[03-06-2018 14:25:04] Transforming net.minecraft.world.chunk.storage.ExtendedBlockStorage Finished.
[03-06-2018 14:25:04] Loading saved data for machine world
[03-06-2018 14:25:04] > 2 spawn points
[03-06-2018 14:25:04] > Next machine id: 2
[03-06-2018 14:25:04] > Players with beds in CM dimension: 0
[03-06-2018 14:25:04] Loading dimension -1 (world) (net.minecraft.server.dedicated.DedicatedServer@19c3fdb8)
[03-06-2018 14:25:04] Loading dimension -2 (world) (net.minecraft.server.dedicated.DedicatedServer@19c3fdb8)
[03-06-2018 14:25:04] Loading dimension 418 (world) (net.minecraft.server.dedicated.DedicatedServer@19c3fdb8)
[03-06-2018 14:25:04] Loading dimension 2 (world) (net.minecraft.server.dedicated.DedicatedServer@19c3fdb8)
[03-06-2018 14:25:04] Loading dimension 1 (world) (net.minecraft.server.dedicated.DedicatedServer@19c3fdb8)
[03-06-2018 14:25:04] Preparing start region for level 0
[03-06-2018 14:25:05] Preparing spawn area: 12%
[03-06-2018 14:25:06] Preparing spawn area: 61%
[03-06-2018 14:25:08] Preparing spawn area: 66%
[03-06-2018 14:25:08] Failed to create block entity minecraft:conductormast
[03-06-2018 14:25:08] java.lang.NoSuchFieldError: CHARGING_RATE
[03-06-2018 14:25:08] at sonar.calculator.mod.common.tileentity.generators.TileEntityConductorMast.<init>(TileEntityConductorMast.java:49) ~[TileEntityConductorMast.class:?]
[03-06-2018 14:25:08] at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:1.8.0_65]
[03-06-2018 14:25:08] at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source) ~[?:1.8.0_65]
[03-06-2018 14:25:08] at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source) ~[?:1.8.0_65]
[03-06-2018 14:25:08] at java.lang.reflect.Constructor.newInstance(Unknown Source) ~[?:1.8.0_65]
[03-06-2018 14:25:08] at java.lang.Class.newInstance(Unknown Source) ~[?:1.8.0_65]
[03-06-2018 14:25:08] at net.minecraft.tileentity.TileEntity.func_190200_a(TileEntity.java:105) [avj.class:?]
[03-06-2018 14:25:08] at net.minecraft.world.chunk.storage.AnvilChunkLoader.loadEntities(AnvilChunkLoader.java:494) [aye.class:?]
[03-06-2018 14:25:08] at net.minecraftforge.common.chunkio.ChunkIOProvider.syncCallback(ChunkIOProvider.java:97) [ChunkIOProvider.class:?]
[03-06-2018 14:25:08] at net.minecraftforge.common.chunkio.ChunkIOExecutor.syncChunkLoad(ChunkIOExecutor.java:94) [ChunkIOExecutor.class:?]
[03-06-2018 14:25:08] at net.minecraft.world.gen.ChunkProviderServer.loadChunk(ChunkProviderServer.java:118) [on.class:?]
[03-06-2018 14:25:08] at net.minecraft.world.gen.ChunkProviderServer.func_186028_c(ChunkProviderServer.java:89) [on.class:?]
[03-06-2018 14:25:08] at net.minecraft.world.gen.ChunkProviderServer.func_186025_d(ChunkProviderServer.java:135) [on.class:?]
[03-06-2018 14:25:08] at net.minecraft.server.MinecraftServer.func_71222_d(MinecraftServer.java:344) [MinecraftServer.class:?]
[03-06-2018 14:25:08] at net.minecraft.server.MinecraftServer.func_71247_a(MinecraftServer.java:314) [MinecraftServer.class:?]
[03-06-2018 14:25:08] at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:270) [nz.class:?]
[03-06-2018 14:25:08] at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:484) [MinecraftServer.class:?]
[03-06-2018 14:25:08] at java.lang.Thread.run(Unknown Source) [?:1.8.0_65]
[03-06-2018 14:25:08] A TileEntity minecraft:conductormast(sonar.calculator.mod.common.tileentity.generators.TileEntityConductorMast) has thrown an exception during loading, its state cannot be restored. Report this to the mod author
[03-06-2018 14:25:08] java.lang.NoSuchFieldError: CHARGING_RATE
[03-06-2018 14:25:08] at sonar.calculator.mod.common.tileentity.generators.TileEntityConductorMast.<init>(TileEntityConductorMast.java:49) ~[TileEntityConductorMast.class:?]
[03-06-2018 14:25:08] at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:1.8.0_65]
[03-06-2018 14:25:08] at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source) ~[?:1.8.0_65]
[03-06-2018 14:25:08] at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source) ~[?:1.8.0_65]
[03-06-2018 14:25:08] at java.lang.reflect.Constructor.newInstance(Unknown Source) ~[?:1.8.0_65]
[03-06-2018 14:25:08] at java.lang.Class.newInstance(Unknown Source) ~[?:1.8.0_65]
[03-06-2018 14:25:08] at net.minecraft.tileentity.TileEntity.func_190200_a(TileEntity.java:105) [avj.class:?]
[03-06-2018 14:25:08] at net.minecraft.world.chunk.storage.AnvilChunkLoader.loadEntities(AnvilChunkLoader.java:494) [aye.class:?]
[03-06-2018 14:25:08] at net.minecraftforge.common.chunkio.ChunkIOProvider.syncCallback(ChunkIOProvider.java:97) [ChunkIOProvider.class:?]
[03-06-2018 14:25:08] at net.minecraftforge.common.chunkio.ChunkIOExecutor.syncChunkLoad(ChunkIOExecutor.java:94) [ChunkIOExecutor.class:?]
[03-06-2018 14:25:08] at net.minecraft.world.gen.ChunkProviderServer.loadChunk(ChunkProviderServer.java:118) [on.class:?]
[03-06-2018 14:25:08] at net.minecraft.world.gen.ChunkProviderServer.func_186028_c(ChunkProviderServer.java:89) [on.class:?]
[03-06-2018 14:25:08] at net.minecraft.world.gen.ChunkProviderServer.func_186025_d(ChunkProviderServer.java:135) [on.class:?]
[03-06-2018 14:25:08] at net.minecraft.server.MinecraftServer.func_71222_d(MinecraftServer.java:344) [MinecraftServer.class:?]
[03-06-2018 14:25:08] at net.minecraft.server.MinecraftServer.func_71247_a(MinecraftServer.java:314) [MinecraftServer.class:?]
[03-06-2018 14:25:08] at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:270) [nz.class:?]
[03-06-2018 14:25:08] at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:484) [MinecraftServer.class:?]
[03-06-2018 14:25:08] at java.lang.Thread.run(Unknown Source) [?:1.8.0_65]
[03-06-2018 14:25:08] Skipping BlockEntity with id minecraft:conductormast
[03-06-2018 14:25:09] Done (7.612s)! For help, type "help" or "?"
[03-06-2018 14:25:09] [java.lang.ThreadGroup:uncaughtException:-1]: java.lang.IllegalArgumentException: timeout value is negative
[03-06-2018 14:25:09] [java.lang.ThreadGroup:uncaughtException:-1]: at java.lang.Thread.sleep(Native Method)
[03-06-2018 14:25:09] [java.lang.ThreadGroup:uncaughtException:-1]: at net.minecraft.server.dedicated.ServerHangWatchdog.run(ServerHangWatchdog.java:83)
[03-06-2018 14:25:09] [java.lang.ThreadGroup:uncaughtException:-1]: at java.lang.Thread.run(Unknown Source)
[03-06-2018 14:25:09] Checking for asteroid config at /home/smpicnic/server/data/./config/advRocketry/asteroidConfig.xml
[03-06-2018 14:25:09] Checking for ore config at /home/smpicnic/server/data/./config/advRocketry/oreConfig.xml
[03-06-2018 14:25:09] Checking for config at /home/smpicnic/server/data/./world/advRocketry/planetDefs.xml
[03-06-2018 14:25:09] Advanced Planet Config file Found!  Loading from file.
[03-06-2018 14:25:09] VoiceServer: Starting up server...
[03-06-2018 14:25:10] Arc Recycling: Removed 0 old recipes
[03-06-2018 14:25:10] Starting recipe profiler for Arc Recycling, using 8 Threads
[03-06-2018 14:25:10] Finished recipe profiler for Arc Recycling, took 45 milliseconds
[03-06-2018 14:25:10] WorldData loading
[03-06-2018 14:25:10] WorldData retrieved
[03-06-2018 14:25:11] Encountered an unexpected exception
[03-06-2018 14:25:11] net.minecraft.util.ReportedException: Ticking block entity
[03-06-2018 14:25:11] at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:771) ~[MinecraftServer.class:?]
[03-06-2018 14:25:11] at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:396) ~[nz.class:?]
[03-06-2018 14:25:11] at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:666) ~[MinecraftServer.class:?]
[03-06-2018 14:25:11] at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:524) [MinecraftServer.class:?]
[03-06-2018 14:25:11] at java.lang.Thread.run(Unknown Source) [?:1.8.0_65]
[03-06-2018 14:25:11] Caused by: java.lang.NoSuchFieldError: CHARGING_RATE
[03-06-2018 14:25:11] at sonar.calculator.mod.common.tileentity.generators.TileEntityConductorMast.<init>(TileEntityConductorMast.java:49) ~[TileEntityConductorMast.class:?]
[03-06-2018 14:25:11] at sonar.calculator.mod.common.block.generators.ConductorMast.func_149915_a(ConductorMast.java:77) ~[ConductorMast.class:?]
[03-06-2018 14:25:11] at net.minecraft.block.Block.createTileEntity(Block.java:1274) ~[aow.class:?]
[03-06-2018 14:25:11] at net.minecraft.world.chunk.Chunk.func_177422_i(Chunk.java:780) ~[axw.class:?]
[03-06-2018 14:25:11] at net.minecraft.world.chunk.Chunk.func_177424_a(Chunk.java:798) ~[axw.class:?]
[03-06-2018 14:25:11] at net.minecraft.world.World.func_175625_s(World.java:2396) ~[amu.class:?]
[03-06-2018 14:25:11] at sonar.calculator.mod.common.tileentity.machines.TileEntityWeatherStation.setAngle(TileEntityWeatherStation.java:55) ~[TileEntityWeatherStation.class:?]
[03-06-2018 14:25:11] at sonar.calculator.mod.common.tileentity.machines.TileEntityWeatherStation.func_73660_a(TileEntityWeatherStation.java:19) ~[TileEntityWeatherStation.class:?]
[03-06-2018 14:25:11] at net.minecraft.world.World.func_72939_s(World.java:1832) ~[amu.class:?]
[03-06-2018 14:25:11] at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:613) ~[oo.class:?]
[03-06-2018 14:25:11] at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:765) ~[MinecraftServer.class:?]
[03-06-2018 14:25:11] ... 4 more
[03-06-2018 14:25:11] This crash report has been saved to: /home/smpicnic/server/data/./crash-reports/crash-2018-06-03_12.25.11-server.txt
[03-06-2018 14:25:11] Stopping server
[03-06-2018 14:25:11] Saving players
[03-06-2018 14:25:11] Saving worlds
[03-06-2018 14:25:11] Saving chunks for level 'world'/overworld
[03-06-2018 14:25:11] Saving chunks for level 'world'/the_nether
[03-06-2018 14:25:11] Saving chunks for level 'world'/the_end
[03-06-2018 14:25:11] Saving chunks for level 'world'/nc_wasteland
[03-06-2018 14:25:11] Saving chunks for level 'world'/Deep Dark
[03-06-2018 14:25:11] Saving chunks for level 'world'/ExtraUtils2_Quarry_Dim
[03-06-2018 14:25:11] Saving chunks for level 'world'/CompactMachines
[03-06-2018 14:25:11] Saving chunks for level 'world'/planet
[03-06-2018 14:25:11] Saving chunks for level 'world'/tartarus
[03-06-2018 14:25:11] Saving chunks for level 'world'/Storage Cell
[03-06-2018 14:25:12] Unloading dimension 0
[03-06-2018 14:25:12] Unloading dimension -1
[03-06-2018 14:25:12] Unloading dimension 1
[03-06-2018 14:25:12] Unloading dimension 4598
[03-06-2018 14:25:12] Unloading dimension -11325
[03-06-2018 14:25:12] Unloading dimension -9999
[03-06-2018 14:25:12] Unloading dimension 144
[03-06-2018 14:25:12] Unloading dimension -2
[03-06-2018 14:25:12] Unloading dimension 418
[03-06-2018 14:25:12] Unloading dimension 2
[03-06-2018 14:25:12] The state engine was in incorrect state SERVER_STOPPING and forced into state SERVER_STOPPED. Errors may have been discarded.
[03-06-2018 14:25:12] > Exception in thread "Server Watchdog" [12:25:12] [Server Shutdown Thread/INFO] [net.minecraft.server.MinecraftServer]: Stopping server
[03-06-2018 14:25:12] > [EXIT STATUS] 10270 exp5 0 0
```

Additional informations : 
- I upgrade Calculator 5.0.4 to 5.0.5 on the same world.
- I have a personal modpack with 110+ mods

If you need it, I can put my list mod here.

**Comment by SonarSonic** [comment] 2018-06-03 11:49
Duplicate of #360

**Comment by guillaumearm** [comment] 2018-06-03 11:58
Are you sure of this ? I didn't use Power Cube in my current map.

**Comment by SonarSonic** [comment] 2018-06-03 12:23
Yes, it's an issue with blocks which have the ability to charge energy items, in your case a conductor mast.

**Comment by SonarSonic** [comment] 2018-06-03 23:22
Fixed version is out.

**Closed as completed by SonarSonic** 2018-06-03 23:22 UTC
