### ISSUE TITLE
Water Buckets Disappearing

### ISSUE THREAD

**Issue by Jeffcole1** [SonarSonic/Calculator#47] opened 2015-11-09 21:45 UTC
Something in Calculator is making water buckets disappear when used in recipes or to fill tanks.  Given that buckets cost 3 iron ingots each to make, this is a big problem.

Steps to Demonstrate:
* Create an instance of Minecraft with the following mods:
  * CodeChickenCore -> NEI
  * Calculator
  * OpenModsLib -> OpenBlocks
  * Mods that add recipes which use water buckets as materials (I used Pam's Harvestcraft)
* In that instance, start a new Survival world with cheats turned on.
* Use NEI's Cheat Mode to spawn the following items:
  * Buckets
  * OpenBlocks Tank
* Fill some of the buckets with water.
* Place one water bucket in your crafting grid and take out the Fresh Water in the output slot.  Notice that you do not get the empty bucket back; it just vanishes.
* Place an OpenBlocks tank in the world and empty a water bucket into it.  The water goes into the tank as expected, but again, the bucket itself disappears.
* Close Minecraft, remove Calculator from the modpack, then re-launch Minecraft and load the Survival world again.  This time, when you repeat the water recipe and tank-filing above, the buckets are returned as expected.

Note: Not all tanks are affected by this issue.  I have tested this with Buildcraft Tanks and Thermal Expansion Portable Tanks, and both return the bucket when filled.  However, recipes from other mods that use water buckets also eat the buckets.

**Comment by AEnterprise** [comment] 2015-11-10 07:34
are you sure calculator is the cause of this issue? does it stop heapening when you remove calculator from the instance?

**Comment by SonarSonic** [comment] 2015-11-10 08:13
I can't possibly see how Calculator is related to this issue :/

**Comment by AEnterprise** [comment] 2015-11-10 13:05
same here, hence the question for him to reproduce without calculator, this sounds like a mod messing with container items

**Comment by Jeffcole1** [comment] 2015-11-10 14:49
Yes, it stops happening when I remove Calculator from the instance.  I haven't actively tried to reproduce it without Calculator.

**Comment by AEnterprise** [comment] 2015-11-10 15:49
it stops heapening without calculator but you didn't try it without calculator? that makes no sense to me

**Comment by Jeffcole1** [comment] 2015-11-10 16:33
Here's what I meant: When Calculator is in my pack, water buckets disappear under the defined conditions.  When I remove Calculator from the pack, they stop disappearing.  I have not rigorously attempted to find a mod or combination of mods, which does not include Calculator, that makes water buckets disappear.

That said, given that removing Calculator from my pack of nearly 100 mods made the problem stop happening, I am inclined to believe that something in Calculator is responsible, either on its own or as a result of an unforeseen interaction with one or more other mods.  I tried testing it in an instance of vanilla + Calculator + NEI, but Calculator does not have any recipes that use water buckets.

Also, I'm not the only one with this issue.  Players of the Resonant Rise pack (which includes Calculator) have reported losing buckets as far back as July: see [here](http://www.resonant-rise.com/topic/6714-witchery-a-bug-or-intentional/), [here](http://www.resonant-rise.com/topic/4217-bugs-configs-and-weirdness-roundup-rr3-edition/page-49#entry45687), and [here](http://www.resonant-rise.com/topic/4217-bugs-configs-and-weirdness-roundup-rr3-edition/page-49#entry45906).

**Comment by AEnterprise** [comment] 2015-11-10 16:44
alright very weird

**Comment by SonarSonic** [comment] 2015-11-10 18:02
Prize to anyone who finds this in the code :)

**Comment by SonarSonic** [comment] 2015-11-10 18:02
what kind of interaction could cause this AEnterprise?
Crafting event maybe?

**Comment by SonarSonic** [comment] 2015-11-10 18:18
can you confirm you are using the latest version 1.8.7

**Comment by Jeffcole1** [comment] 2015-11-10 19:07
I first downloaded the mod at version 1.8.4.  When I discovered the problem, I tried each successive version up to 1.8.7, and none of them fixed it.

**Comment by AEnterprise** [comment] 2015-11-10 21:11
@Jeffcole1 you heapen to know the first version that introduced it

@SonarSonic no ide of the cause atm, i'll try to look intro it tomorow

**Comment by Jeffcole1** [comment] 2015-11-10 21:34
So I went ahead and tested older versions, and it looks like the issue first appears in [1.6.9](http://minecraft.curseforge.com/projects/calculator/files/2239089).  In 1.6.8 and before, empty buckets come back just fine, but in 1.6.9 and later, they vanish.

**Comment by SonarSonic** [comment] 2015-11-10 22:03
interesting I'll have a look at the changelog

**Comment by SonarSonic** [comment] 2015-11-10 22:24
I managed to recreate this but still no longer any further idea if this is Calculator fault or not tbh.
@boq  Might you have any idea how to resolve this issue??

**Comment by AEnterprise** [comment] 2015-11-11 08:08
alright, thanks @Jeffcole1 for tracing that down, now we know between what versions it starts it's possible to try to trace it

**Comment by boq** [comment] 2015-11-11 08:26
@SonarSonic Sorry, but no idea. Here's our code for filling tanks from buckets:
[Part 1](https://github.com/OpenMods/OpenBlocks/blob/master/src/main/java/openblocks/common/tileentity/TileEntityTank.java#L242) [Part 2](https://github.com/OpenMods/OpenModsLib/blob/master/src/main/java/openmods/utils/ItemUtils.java#L26)

Note: this code incorrectly assumes that only non-stackable items can have containers. I will fix it soon, but it probably doesn't make a difference for buckets.

**Comment by Tedyhere** [comment] 2015-11-13 05:41
Can confirm this, just tested in Modlife 3 pack.  Thermal Expansion recipe for paper.. 1 water bucket with 4 sawdust u/d/l/r of the bucket gives 2 paper and eats the water bucket. Also Immersive Engineering radiator block recipe eats the bucket.  Also shapeless recipes such as treated leather from Iron backpacks. :/

**Comment by SonarSonic** [comment] 2015-11-14 23:37
I've been looking into this tonight. Still no clue.

**Comment by SonarSonic** [comment] 2015-11-22 12:29
Fixed in 1.8.9!!! :) It was a problem with the RecipeHelper although I still don't really understand how

**Closed by SonarSonic** 2015-11-22 12:29 UTC
