### ISSUE TITLE
Storage Chamber [Analysed] doesn't accept some circuits; when forced in with a hopper they turn into others

### ISSUE THREAD

**Issue by IChris2698I** [SonarSonic/Calculator#179] opened 2016-09-30 05:02 UTC
I'm playing All The Mods v 1.31, with Calculator-1.9.4-3.1.2.jar on Minecraft 1.10.2. Hmm, come to think of it, maybe that's the problem. CurseForge says Calculator-1.9.4-3.1.2 is compatible with Minecraft 1.10.2 though. Eh, disregard if you're not accepting 1.10.2 issues.

I'm turning a few stacks of cobble into circuits with a Precision Chamber + Processing Chamber + Analysing Chamber, and looking to store the analysed circuits in a Storage Chamber. Now, sometimes I get stable circuits, so I need two Storage Chambers (those things are pretty expensive).

The Storage Chamber with stable circuits works fine, and I've found at least one of each stable circuit and shift-clicked them in with no problem.

With analysed (not stable) circuits, the storage chamber is... different. It won't accept 5 of the 15 circuits, and when forced in with a vanilla hopper, they turn into other circuits. Two turn into other unanalysed circuits with items hiding in them, two turn into analysed circuits with no items, and one turns into a stable circuit with no items.

![2016-09-29_22 02 02](https://cloud.githubusercontent.com/assets/17462176/18981150/59bdcca4-8690-11e6-8868-ea99d0e9eef3.png)

**Comment by SonarSonic** [comment] 2016-09-30 11:17
Duplicate of #177

**Closed as completed by SonarSonic** 2016-09-30 11:17 UTC
Labels: duplicate
