### ISSUE TITLE
Can't put items into the calculator

### ISSUE THREAD

**Issue by HerrEragon** [SonarSonic/Calculator#9] opened 2015-07-08 20:32 UTC
everytime i try to put a item into the calculator my inventory gets rearranged and the item vanishes for a short time. 

I'm using InventoryTweaks

**Comment by DrWhoCares** [comment] 2015-07-08 20:32
Which version?

**Comment by SonarSonic** [comment] 2015-07-08 22:51
Yeah this one has been around for a long time. Inventory Tweaks denied this was them, i'm still unsure, but i'm curious to know which version you on, I started from scratch on all the Calculator Containers to see if I could remove the problem.

**Comment by HerrEragon** [comment] 2015-07-09 10:17
using Calculator-1.7.10-1.7.5 and InventoryTweaks-1.58-147

**Comment by SonarSonic** [comment] 2015-07-09 10:26
Damn, I hoped i'd fixed this. Could you possible remove Inv Tweaks and see if you still get it?

**Comment by HerrEragon** [comment] 2015-07-09 11:27
seems like you fixed it it was somehow specific to that world. After a minecraft restart and testing with only some mods at a time it works even with every mod active. Just not in worlds i created before the testing.

**Comment by SonarSonic** [comment] 2015-07-09 11:57
It's possible, the research changes would have only taken place after. Are you getting this problem on both Servers and Client? Tell me if it comes back though. Thank you :)

**Comment by HerrEragon** [comment] 2015-07-10 22:06
Found out when the problem occures. always after i tried to shift  click a item into the calculator

**Comment by SonarSonic** [comment] 2015-07-11 12:43
Interesting, shame I haven't fixed it yet, I'll have to look carefully through the code

**Comment by DrWhoCares** [comment] 2015-07-20 20:03
This may have been fixed in newest version, if it continues, please say.

**Comment by SonarSonic** [comment] 2015-07-26 00:59
I don't think it is. It is an on going bug

**Comment by Tedyhere** [comment] 2015-07-30 03:33
Using version 1.7.8 with forge 1492 the Issue where if I Shift click in any inventory screen it totally breaks your GUI.  When in any machine or calculator gui I cannot pick up items from my inventory, the inventory scrambles, items appear to dupe or disappear but they dont really.  Restarting Minecraft fixes the issue until you Shift Click again.  I can reproduce this with and without NEI and Inv Tweaks .

**Comment by SonarSonic** [comment] 2015-07-31 22:27
Still no idea :(

**Comment by SonarSonic** [comment] 2015-08-03 23:02
Are you running the latest version of Inv Tweaks?

**Comment by Tedyhere** [comment] 2015-08-03 23:24
I will triple check. Before it did it with or without inv tweaks. I'll report back in a bit

**Comment by SonarSonic** [comment] 2015-08-03 23:25
Really? I've never witnessed it without inv tweaks! I can't reproduce this bug ever on my computer. I only see on other peoples servers.

**Comment by Tedyhere** [comment] 2015-08-05 21:57
I have a video coming that shows the issue, both with and without Inv tweaks :/  I even went thought the forge logs and couldn't find anything odd.  Seems like a server desync or something odd not getting passed from the client to the server.  Even have it on Single Player sometimes

**Comment by Tedyhere** [comment] 2015-08-05 22:15
The promised video showing the issue. http://youtu.be/-BSLNWsnM4g

**Comment by SonarSonic** [comment] 2015-08-05 23:55
Very useful. Could you possible do me a big favour, if I give you a slightly altered version of the mod as in an unreleased one. If it sorts the error out yay! If not I'll need to do a lot of thinking. I think it could be a sync issue.

**Comment by Tedyhere** [comment] 2015-08-05 23:57
Absolutely I am more than happy to help test to make things good for the mod.

**Comment by SonarSonic** [comment] 2015-08-06 00:06
Building with changes now :)

**Comment by SonarSonic** [comment] 2015-08-06 00:07
https://www.dropbox.com/s/96kszbtpfppp29b/Calculator-1.7.10-1.7.8%20-%20Unreleased.jar?dl=0

**Comment by Tedyhere** [comment] 2015-08-06 00:13
testing now

**Comment by SonarSonic** [comment] 2015-08-06 00:14
Awesome thanks! Have you experienced this with any other calculators? e.g. Storage Module, Flawless Calculator? btw I only changed the Normal Calculator's code so don't bother testing anything else.

**Comment by Tedyhere** [comment] 2015-08-06 00:16
Yes with the scientific... that's as far as I have gotten with the mod.. I believe the stone separator too.  And unfortunately this fix didn't fix the issue

**Comment by SonarSonic** [comment] 2015-08-06 00:17
okay, still good to know I can rule out that code :/ Are you sure about Stone Separator fairly sure this is only a Calculator thing :/ At least I hope so.

**Comment by SonarSonic** [comment] 2015-08-06 00:18
If your still in the world it would be really useful if you could try the Storage Module

**Comment by Tedyhere** [comment] 2015-08-06 00:20
Ill load up single player and try some stuff.

**Comment by Tedyhere** [comment] 2015-08-06 00:29
Storage module works perfectly... interestingly enough the calculator works part of the time.. I made a stack of reinforced stone a few times shift clicking but than it broke... I have no clue what is up

**Comment by SonarSonic** [comment] 2015-08-06 00:35
Storage Module works :/ Very interesting. Can i give you another version of Calculator? You will have to backdate after cause Crafting won't work properly yet but moving stacks around might... fingers crossed.

**Comment by Tedyhere** [comment] 2015-08-06 00:37
Sure.. I am testing other modules right now to see what's up

**Comment by SonarSonic** [comment] 2015-08-06 00:41
Okay crafting is completely disabled so don't worry about that. https://www.dropbox.com/s/7lr3aq8kqmpr2k8/Calculator-1.7.10-1.7.8%20-%20Unreleased%202.jar?dl=0

**Comment by Tedyhere** [comment] 2015-08-06 00:50
Ok that seems to work.. only odd thing I saw and it may be nothing is when shift clicking into the newly coded calculator first shift click goes into the second slot and second shift click goes into the results slot.

**Comment by Tedyhere** [comment] 2015-08-06 01:53
I just had a thought.. I am using Java 8  could that be the issue?

**Comment by SonarSonic** [comment] 2015-08-06 08:29
Yes! I can probably fix it now i'll probably post the new version tonight :). No the Java Version should be fine, i'm running 8 to.

**Comment by SonarSonic** [comment] 2015-08-07 01:01
Okay here is another version. It would be awesome if you could try out every Calculator including Dynamic Crafting on the Flawless Calculator since all the systems have been replaced. Thank you!
https://www.dropbox.com/s/yvgr5p36gqi7nqo/Calculator-1.7.10-1.7.8%20-%20Unreleased%203.jar?dl=0

**Comment by SonarSonic** [comment] 2015-08-08 13:31
I published a release with what I hope has fixed it

**Comment by Tedyhere** [comment] 2015-08-08 13:38
sorry been a busy few days. I'll be sure to test the release

**Comment by SonarSonic** [comment] 2015-08-08 14:09
awesome let me know it's all good :)

**Comment by Tedyhere** [comment] 2015-08-09 23:12
Yeah it's doing it with and without inv tweaks, SSP and SMP seems like a sync issue for sure

**Comment by SonarSonic** [comment] 2015-08-09 23:13
Does it work if your in Creative Mode?

**Comment by Tedyhere** [comment] 2015-08-09 23:15
Doesn't work in either creative or survival.  We think it has to do with the RF usage possibly

**Comment by SonarSonic** [comment] 2015-08-09 23:16
Yeah that's what I think too

**Comment by Tedyhere** [comment] 2015-08-09 23:17
Well Gany thinks that's the issue.. see if he notices anything you haven't noticed

**Comment by SonarSonic** [comment] 2015-08-09 23:17
Does Flawless Calculator work? Cause that doesn't use energy

**Comment by Tedyhere** [comment] 2015-08-09 23:21
let me check

**Comment by Tedyhere** [comment] 2015-08-09 23:23
Gany left his thoughts.. see if this makes sense? http://pastebin.com/WcuZXvRM

**Comment by Tedyhere** [comment] 2015-08-09 23:23
And no the flawless doesn't work

**Comment by SonarSonic** [comment] 2015-08-09 23:26
Yes this could possibly cause the issue, not sure where I'm writing to the client though but I can run some tests.

**Comment by Tedyhere** [comment] 2015-08-09 23:27
He didn't proof read the code but he believes this is the issue

**Comment by SonarSonic** [comment] 2015-08-09 23:54
I think he is correct but I still can't work out how to fix just yet because I can't see this glitch on my own client/server

**Comment by Tedyhere** [comment] 2015-08-09 23:58
Would it help if I whitelisted you to my server? I have the pack available on the curse client also

**Comment by SonarSonic** [comment] 2015-08-10 00:01
I'm not sure because I don't think i'd be able to change my client code while on the server but I've found where I'm writing to client instead of server.

**Comment by Tedyhere** [comment] 2015-08-10 00:03
ahh cool, hope you got the glitch under control now! I know it's driving you and me nuts lol

**Comment by SonarSonic** [comment] 2015-08-10 00:03
i don't know about under control haha

**Comment by SonarSonic** [comment] 2015-08-10 00:31
Would you be able to test a version quickly ??

**Comment by Tedyhere** [comment] 2015-08-10 00:37
Yes I can

**Comment by SonarSonic** [comment] 2015-08-10 00:45
Thank you :) https://www.dropbox.com/s/tpm9ja6pem46ilj/Calculator-1.7.10-1.8.1.jar?dl=0
This is with Ganymede's suggestions

**Comment by Tedyhere** [comment] 2015-08-10 01:27
Yeah, no Joy here in mudville.  Still doing it

**Comment by SonarSonic** [comment] 2015-08-10 01:29
maybe if I download your mod pack i'll get the problem on my computer? i'll try it

**Comment by Tedyhere** [comment] 2015-08-10 01:38
Hope you figure something out.. I've tried with and without inv tweaks :/

**Comment by SonarSonic** [comment] 2015-08-10 01:38
so annoying and confusing but if I can recreate it quickly i'll be able to fix it quicker

**Comment by Tedyhere** [comment] 2015-08-10 01:41
I don't think you'll have an issue recreating it.  Happens to all my players

**Comment by Tedyhere** [comment] 2015-08-10 02:24
You see the bug I been seeing now?

**Comment by SonarSonic** [comment] 2015-08-10 10:59
I couldn't launch with those mods from client on my dev. I could reproduce it on a separate server but only sometimes. In worked perfectly on my client with all mods installed, so no closer really but I can test without needing you to help, just about.

**Comment by SonarSonic** [comment] 2015-08-10 15:01
Okay I think I've actually done it now, it was a problem with Client and Server not syncing when open the GUI

**Comment by SonarSonic** [comment] 2015-08-10 17:07
Should be fixed in latest version.

**Closed by SonarSonic** 2015-08-10 17:07 UTC
Labels: bug
