### ISSUE TITLE
1.11.2 Circuit Transfer Corruption/Crash

### ISSUE THREAD

**Issue by BigFriendlyJakey** [SonarSonic/Calculator#273] opened 2017-09-05 11:36 UTC
Please fill out the details below before contributing

 * Forge Version: 1.11.2-forge1.11.2-13.20.1.2388
 * Calculator Version: Calculator-1.11.2-4.0.0
 * SonarCore Version: SonarCore-1.11.2-4.0.0
 * Multiplayer or Singleplayer: Single
 * Crash Report Link: https://pastebin.com/zbch2QYw
 * Affected Features: Cannot access world or delete blocks in MCEdit
 * Description: I added transfer upgrades to two precision chambers feeding into separate processing chambers, and about two seconds later the game crashed & I can no longer access the world or delete the blocks causing the crash due to "corruption" (according to MCEdit).

**Comment by SonarSonic** [comment] 2017-09-19 11:35
Duplicate of #283

**Closed as completed by SonarSonic** 2017-09-19 11:35 UTC
