### ISSUE TITLE
[1.10] Reinforced chest - stacks of 256 items are invisible

### ISSUE THREAD

**Issue by kwpugh** [SonarSonic/Calculator#114] opened 2016-06-27 00:47 UTC
Forge: 1996
Mod: Calculator-1.9.4-3.0.0.jar

The reinforced chest accepts stacks up to 256 items each and the stacks go invisible at 256.

**Comment by SonarSonic** [comment] 2016-06-27 17:59
interesting. thanks for letting me know

**Comment by SonarSonic** [comment] 2016-06-27 18:04
I couldn't reproduce this could you possibly provide any further info. Are you using any inventory mods?

**Comment by kwpugh** [comment] 2016-06-27 18:19
We are using InventoryTweaks.   Is that what you mean by inventory mods?

**Comment by SonarSonic** [comment] 2016-06-27 23:53
yeah that could possibly be the issue. no mods are 100% stable on 1.10

**Comment by MineWitherMC** [comment] 2016-06-28 10:04
Inventory tweaks almost "conflicts" with Calculator, you can't see 256-stacks, use Ender Diamond tools etc.

**Comment by hron84** [comment] 2016-08-09 09:59
Let me invite @Kobata in this thread. Maybe he has some idea about this problem.

**Comment by ErsatzIncline** [comment] 2016-09-10 01:43
Similar thing is occurring with circuit storage, probably because of similar interaction (again inventory tweaks). Posted under a separate thread sorry.

**Comment by SonarSonic** [comment] 2016-09-22 01:50
Should be fixed

**Closed as completed by SonarSonic** 2016-09-22 01:50 UTC
Labels: non reproducible
